USE [Proyecto2]
GO

/****** Object:  Table [dbo].[PagoFactura]    Script Date: 23/5/2024 22:30:29 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[PagoFactura](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[Numero] [nvarchar](20) NOT NULL,
	[FechaPago] [date] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

