USE [NewTelefoneria]
GO

/****** Object:  Table [dbo].[Descripcion]    Script Date: 9/6/2024 11:40:47 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Descripcion](
	[Id] [int] NOT NULL,
	[TipoDescripcion] [varchar](64) NOT NULL,
 CONSTRAINT [PK__Descripc__3213E83FAEFFA916] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

