USE [NewTelefoneria]
GO

/****** Object:  Table [dbo].[TipoMinutos]    Script Date: 9/6/2024 11:43:01 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[TipoMinutos](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[TipoMinuto] [varchar](64) NOT NULL,
 CONSTRAINT [PK_TipoMinutos_1] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

